## Load packages
library(RPostgreSQL, warn.conflicts = F)
library(pool, warn.conflicts = F)
library(DBI, warn.conflicts = F)
library(tidyverse, warn.conflicts = F)
library(XML)
library(xml2, warn.conflicts = F)
library(rvest, warn.conflicts = F)
library(data.table, warn.conflicts = F)
library(hablar, warn.conflicts = F)
library(stringr)
library(stringi, warn.conflicts = F)
library(foreach, warn.conflicts = F)
library(parallel)
library(rlang, warn.conflicts = F)
library(htmlTable, warn.conflicts = F)
library(furrr)
library(future)
library(telegram.bot)
library(openxlsx)
library(gridExtra, warn.conflicts = F)
library(retry, warn.conflicts = F)
library(V8)